// SPDX-License-Identifier: MIT OR Apache-2.0

//! In-place signed-chain rotation planner (#181 Phase 2a).
//!
//! This module is the pure-fn planning layer for `aegis-boot update
//! --apply`. Given a Phase-1 ESP diff, it produces an ordered list
//! of rotation steps naming exactly what would be backed up, staged,
//! rotated, and verified on each of the 6 canonical ESP slots.
//!
//! **Phase 2a ships the planner + rollback analyzer + unit tests.**
//! No destructive code path is reachable in this PR — the CLI
//! surface (`--apply --experimental-apply`) dry-prints the plan
//! and returns without calling any mtools subprocess. Phase 2b
//! wires the executor (backup → stage → verify → rotate → verify
//! → leave .bak in place) with OVMF E2E validation.
//!
//! # Why split
//!
//! FAT32 has no journal. The "atomic" in `--atomic-replace` means
//! "bounded rollback + explicit verification," not "single-syscall
//! transaction." Shipping the planner first lets reviewers validate
//! the rotation shape (ordering, rollback semantics) without the
//! executor in scope. Phase 2b's review then focuses on one
//! question: "does the executor do what the planner said it would?"
//!
//! # What the planner produces
//!
//! One [`RotationStep`] per canonical ESP slot that [`would_change`]
//! (same predicate as Phase-1's `EspFileDiff::would_change`).
//! Unchanged slots are skipped entirely — the executor never
//! touches them. The plan also carries the expected pre- and
//! post-rotation sha256 per step, so the executor's post-rotate
//! verify has a concrete target rather than trusting the filesystem.
//!
//! # Rollback analyzer
//!
//! The executor may partially complete — say, files 1-3 rotated,
//! file 4 fails mid-copy. The rollback analyzer ([`rollback_plan`])
//! takes the set of *completed* rotations plus the set of *staged-
//! but-not-rotated* `.new` files and emits the unwind: restore
//! .bak on rotated files, delete .new on staged-but-not-rotated.
//!
//! # Out of scope for 2a
//!
//! - Subprocess execution (Phase 2b)
//! - CA signature verification on the staged bytes (Phase 3)
//! - TOCTOU + path-validation hardening (Phase 3)
//! - Attestation manifest `update_history` field (Phase 4)
//!
//! Tracking: epic [#181](https://github.com/aegis-boot/aegis-boot/issues/181).

// Phase 2a ships `plan_rotation()` + `print_rotation_plan` as live
// code, but the executor-side types (`StepProgress`, `RollbackAction`,
// `rollback_plan`) have no consumer until Phase 2b wires the
// destructive executor. Keep them compiled + unit-tested now so the
// Phase 2b PR is "wire the planner's outputs into mtools calls",
// not "re-derive the rollback logic under review pressure."
#![allow(dead_code)]

use crate::update::EspFileDiff;

/// One ESP slot's worth of rotation work. Generated by
/// [`plan_rotation`] from a Phase-1 diff row.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct RotationStep {
    /// Role label — `shim`, `grub`, `grub_cfg_boot`,
    /// `grub_cfg_ubuntu`, `kernel`, `initrd`. Matches
    /// `EspFileDiff::role`.
    pub role: &'static str,
    /// Canonical ESP destination with leading `/`. Example:
    /// `/EFI/BOOT/BOOTX64.EFI`.
    pub esp_path: &'static str,
    /// Sha256 currently on the stick for this slot. The executor
    /// hashes the staged `.bak` copy and asserts this value matches
    /// — detects silent tampering between planner and executor runs.
    pub current_sha256: String,
    /// Sha256 the host-side source a fresh flash would install.
    /// The executor's post-rotate readback hashes the rotated
    /// destination and asserts this value matches.
    pub fresh_sha256: String,
}

/// Build the ordered rotation plan from a Phase-1 ESP diff.
///
/// Only slots where [`EspFileDiff::would_change`] is true produce
/// a step. Unchanged slots and UNKNOWN slots (either side's hash
/// couldn't be computed) are elided — the executor skips them
/// entirely. This matches the planner's contract: we only rotate
/// what we're confident differs, and the executor's job is to make
/// that change happen safely.
pub(crate) fn plan_rotation(diff: &[EspFileDiff]) -> Vec<RotationStep> {
    diff.iter()
        .filter(|row| row.would_change())
        .filter_map(|row| {
            // would_change() is only true when both sides are Ok(_);
            // the unwraps here are infallible under that invariant.
            // Defend with a match anyway so a future refactor of
            // would_change() can't silently produce a panicking
            // planner.
            let current = row.current.as_ref().ok()?.clone();
            let fresh = row.fresh.as_ref().ok()?.clone();
            Some(RotationStep {
                role: row.role,
                esp_path: row.esp_path,
                current_sha256: current,
                fresh_sha256: fresh,
            })
        })
        .collect()
}

/// Records the outcome of one rotation step's progress through the
/// executor. Used by [`rollback_plan`] to decide what to undo.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum StepState {
    /// Executor hasn't started this step yet.
    Pending,
    /// `.new` staged on the ESP, but the rename-over hasn't fired.
    /// Rollback: delete `.new`.
    Staged,
    /// Rename-over complete, file rotated in place; `.bak` exists.
    /// Rollback: delete rotated, rename `.bak` → original.
    Rotated,
}

/// Per-step progress tracking for the executor. One per
/// [`RotationStep`] in the same order as the plan.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct StepProgress {
    pub step: RotationStep,
    pub state: StepState,
}

/// One rollback action. The executor translates these into mtools
/// subprocess calls in Phase 2b; 2a just names them so the planner
/// logic is unit-testable without subprocess mocking.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum RollbackAction {
    /// `mdel ::/<esp_path>.new` — clean up a stage-only file.
    DeleteStaged { esp_path: &'static str },
    /// `mdel ::/<esp_path>` then `mren ::/<esp_path>.bak
    /// ::/<esp_path>` — restore the pre-rotation file from backup.
    RestoreFromBak { esp_path: &'static str },
}

/// Compute the rollback sequence for a partially-executed plan.
/// Walks the progress list in REVERSE order — the most-recent
/// rotation is undone first so any shared-parent-directory state
/// (if we ever grow that case) unwinds in last-in-first-out
/// order. Pending steps contribute no rollback actions.
///
/// Returns an empty Vec when no state-carrying step was reached
/// (all pending), which is the "nothing to undo" case the executor
/// hits when pre-flight validation fails before the first write.
pub(crate) fn rollback_plan(progress: &[StepProgress]) -> Vec<RollbackAction> {
    progress
        .iter()
        .rev()
        .filter_map(|p| match p.state {
            StepState::Pending => None,
            StepState::Staged => Some(RollbackAction::DeleteStaged {
                esp_path: p.step.esp_path,
            }),
            StepState::Rotated => Some(RollbackAction::RestoreFromBak {
                esp_path: p.step.esp_path,
            }),
        })
        .collect()
}

/// Sources the executor pulls rotated file bytes from. One host-side
/// path per rotation role. The executor mcopies these into `.new`
/// slots on the ESP, which Phase 2a's planner never sees — the planner
/// only knows hashes, not paths. Caller (CLI layer) resolves the paths
/// from [`crate::update::resolve_host_chain`] output.
#[cfg_attr(not(test), allow(dead_code))]
pub(crate) struct RotationSources<'a> {
    pub shim: &'a std::path::Path,
    pub grub: &'a std::path::Path,
    pub grub_cfg: &'a std::path::Path,
    pub kernel: &'a std::path::Path,
    pub combined_initrd: &'a std::path::Path,
}

impl<'a> RotationSources<'a> {
    /// Resolve the host-side source file for a rotation step based on
    /// the step's role label. Returns `None` for an unrecognized role,
    /// which the executor treats as a hard error — an unknown role in
    /// the plan is a planner/executor drift bug, not a recoverable
    /// runtime condition.
    #[cfg_attr(not(test), allow(dead_code))]
    pub(crate) fn source_for(&self, role: &str) -> Option<&'a std::path::Path> {
        match role {
            "shim" => Some(self.shim),
            "grub" => Some(self.grub),
            "grub_cfg_boot" | "grub_cfg_ubuntu" => Some(self.grub_cfg),
            "kernel" => Some(self.kernel),
            "initrd" => Some(self.combined_initrd),
            _ => None,
        }
    }
}

/// Execute the planned rotation against `part1_dev`. Returns the
/// progress trace so the caller can pass it to [`rollback_plan`] on
/// failure and drive the unwind via [`execute_rollback`].
///
/// Contract per ADR-free Phase 2b design:
/// 1. For each step (in plan order):
///    a. `mcopy` the fresh host source to `<esp_path>.new`
///    b. Mark the step `Staged`
///    c. `mren <esp_path> <esp_path>.bak` (preserves previous bytes)
///    d. `mren <esp_path>.new <esp_path>` (commits the new bytes)
///    e. Mark the step `Rotated`
/// 2. On any subprocess failure: return `Err(reason, progress)` so the
///    caller can decide whether to rollback or surface the partial state
///    to the operator.
///
/// This function does NOT call [`execute_rollback`] itself — the CLI
/// layer owns that decision so an operator running with `--no-rollback`
/// (future flag) can inspect the partial state.
///
/// Linux-only because it consumes `direct_install::build_*_argv`
/// helpers which are `#![cfg(target_os = "linux")]`. macOS / Windows
/// rotation adapters ship under #367 Phase D.
///
/// # Errors
///
/// Returns `Err((reason, progress))` with the progress at the point of
/// failure. Caller typically threads `progress` into [`rollback_plan`].
#[cfg(target_os = "linux")]
#[cfg_attr(not(test), allow(dead_code))]
pub(crate) fn execute_rotation(
    steps: &[RotationStep],
    part1_dev: &std::path::Path,
    sources: &RotationSources<'_>,
) -> Result<Vec<StepProgress>, (String, Vec<StepProgress>)> {
    let dev = part1_dev.display().to_string();
    let mut progress: Vec<StepProgress> = steps
        .iter()
        .map(|s| StepProgress {
            step: s.clone(),
            state: StepState::Pending,
        })
        .collect();

    for i in 0..steps.len() {
        let step = &steps[i];
        let Some(src) = sources.source_for(step.role) else {
            return Err((
                format!(
                    "no host-side source for role '{}' — planner/executor drift",
                    step.role
                ),
                progress,
            ));
        };

        // mtools wants `::/`-rooted paths; the planner stores bare
        // `/vmlinuz`-style paths to match `ESP_DIFF_SLOTS`. Add the
        // `::` drive-prefix here so mcopy/mren operate on the image,
        // not the host filesystem (which is what happens silently if
        // the `::` is missing — the file ends up in `/` on the host
        // and the subsequent mren can't find it on the ESP).
        let mtools_orig = format!("::{}", step.esp_path);
        let mtools_new = format!("::{}.new", step.esp_path);
        let mtools_bak = format!("::{}.bak", step.esp_path);

        // Stage: mcopy src → <esp_path>.new
        let mcopy = crate::direct_install::build_mcopy_argv(&dev, src, &mtools_new);
        let mcopy_refs: Vec<&str> = mcopy.iter().map(String::as_str).collect();
        if let Err(e) = run_mtool(&mcopy_refs) {
            return Err((format!("mcopy {mtools_new}: {e}"), progress));
        }
        progress[i].state = StepState::Staged;

        // Rotate step 1: mren <esp_path> → <esp_path>.bak
        let mren_bak = crate::direct_install::build_mren_argv(&dev, &mtools_orig, &mtools_bak);
        let mren_bak_refs: Vec<&str> = mren_bak.iter().map(String::as_str).collect();
        if let Err(e) = run_mtool(&mren_bak_refs) {
            return Err((format!("mren {mtools_orig} → {mtools_bak}: {e}"), progress));
        }

        // Rotate step 2: mren <esp_path>.new → <esp_path>
        let mren_new = crate::direct_install::build_mren_argv(&dev, &mtools_new, &mtools_orig);
        let mren_new_refs: Vec<&str> = mren_new.iter().map(String::as_str).collect();
        if let Err(e) = run_mtool(&mren_new_refs) {
            // Mid-rotation failure — .bak exists, .new exists, <esp_path> missing.
            // State is `Staged` still (we haven't reached Rotated); rollback_plan
            // will DeleteStaged, but the pre-rotation file is now at .bak. Caller
            // must also restore .bak → original via a manual recovery step, or the
            // executor can be extended to represent this tri-state. For now surface
            // the partial state with a clear error.
            return Err((
                format!(
                    "mren {mtools_new} → {mtools_orig}: {e} — .bak preserved, manual recovery: mren {mtools_bak} {mtools_orig}"
                ),
                progress,
            ));
        }
        progress[i].state = StepState::Rotated;
    }

    Ok(progress)
}

/// Execute the rollback actions produced by [`rollback_plan`] against
/// the same ESP device. Walks the actions in order — since
/// [`rollback_plan`] emits them in reverse plan order (last-rotated
/// first), executing in-order is the LIFO semantics documented on
/// that function.
///
/// Linux-only — same rationale as [`execute_rotation`].
///
/// # Errors
///
/// Returns a vec of per-action error strings rather than short-circuiting
/// on first failure — rollback is best-effort, and the caller wants to
/// know every slot that's in an indeterminate state so the operator can
/// physically inspect + reflash.
#[cfg(target_os = "linux")]
#[cfg_attr(not(test), allow(dead_code))]
pub(crate) fn execute_rollback(
    actions: &[RollbackAction],
    part1_dev: &std::path::Path,
) -> Result<(), Vec<String>> {
    let dev = part1_dev.display().to_string();
    let mut errs: Vec<String> = Vec::new();
    for action in actions {
        match action {
            RollbackAction::DeleteStaged { esp_path } => {
                // Same `::/`-prefix convention as execute_rotation.
                let mtools_new = format!("::{esp_path}.new");
                let mdel = crate::direct_install::build_mdel_argv(&dev, &mtools_new);
                let mdel_refs: Vec<&str> = mdel.iter().map(String::as_str).collect();
                if let Err(e) = run_mtool(&mdel_refs) {
                    errs.push(format!("rollback DeleteStaged {mtools_new}: {e}"));
                }
            }
            RollbackAction::RestoreFromBak { esp_path } => {
                let mtools_orig = format!("::{esp_path}");
                let mtools_bak = format!("::{esp_path}.bak");
                // Delete the current (rotated) file, then rename .bak back over it.
                let mdel = crate::direct_install::build_mdel_argv(&dev, &mtools_orig);
                let mdel_refs: Vec<&str> = mdel.iter().map(String::as_str).collect();
                if let Err(e) = run_mtool(&mdel_refs) {
                    errs.push(format!("rollback delete-before-restore {mtools_orig}: {e}"));
                    continue;
                }
                let mren = crate::direct_install::build_mren_argv(&dev, &mtools_bak, &mtools_orig);
                let mren_refs: Vec<&str> = mren.iter().map(String::as_str).collect();
                if let Err(e) = run_mtool(&mren_refs) {
                    errs.push(format!(
                        "rollback RestoreFromBak {mtools_bak} → {mtools_orig}: {e}"
                    ));
                }
            }
        }
    }
    if errs.is_empty() { Ok(()) } else { Err(errs) }
}

/// Thin sudo wrapper local to the executor. Mirrors `direct_install::
/// run_sudo` but lives here so `update_apply` has no cross-module
/// coupling through a private helper. Fails closed on any non-zero
/// exit with the subprocess's stderr rolled up.
#[cfg(target_os = "linux")]
#[cfg_attr(not(test), allow(dead_code))]
fn run_mtool(argv: &[&str]) -> Result<(), String> {
    let out = std::process::Command::new("sudo")
        .args(argv)
        .output()
        .map_err(|e| format!("{} exec failed: {e}", argv.first().unwrap_or(&"?")))?;
    if !out.status.success() {
        return Err(format!(
            "{} exited {}: {}",
            argv.first().unwrap_or(&"?"),
            out.status,
            String::from_utf8_lossy(&out.stderr).trim()
        ));
    }
    Ok(())
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::missing_panics_doc
)]
mod tests {
    use super::*;

    fn mk_diff_row(
        role: &'static str,
        esp_path: &'static str,
        current: Result<&str, &str>,
        fresh: Result<&str, &str>,
    ) -> EspFileDiff {
        EspFileDiff {
            role,
            esp_path,
            current: current.map(str::to_string).map_err(str::to_string),
            fresh: fresh.map(str::to_string).map_err(str::to_string),
        }
    }

    #[test]
    fn plan_rotation_skips_unchanged_and_unknown_rows() {
        let diff = vec![
            // Unchanged — same hash both sides → skip.
            mk_diff_row("shim", "/EFI/BOOT/BOOTX64.EFI", Ok("a"), Ok("a")),
            // Changed — would rotate.
            mk_diff_row("grub", "/EFI/BOOT/grubx64.efi", Ok("b"), Ok("c")),
            // UNKNOWN (current side errored) — skip.
            mk_diff_row("kernel", "/vmlinuz", Err("no mtype"), Ok("d")),
            // UNKNOWN (fresh side errored) — skip.
            mk_diff_row("initrd", "/initrd.img", Ok("e"), Err("missing src")),
            // Another changed one.
            mk_diff_row("grub_cfg_boot", "/EFI/BOOT/grub.cfg", Ok("f"), Ok("g")),
        ];
        let plan = plan_rotation(&diff);
        assert_eq!(plan.len(), 2, "only CHANGED rows should produce a step");
        assert_eq!(plan[0].role, "grub");
        assert_eq!(plan[0].current_sha256, "b");
        assert_eq!(plan[0].fresh_sha256, "c");
        assert_eq!(plan[1].role, "grub_cfg_boot");
    }

    #[test]
    fn plan_rotation_preserves_diff_order() {
        // Ensure the planner doesn't reshuffle — order matters for
        // the executor's pre-verify chain (each step depends on
        // the prior one having committed).
        let diff = vec![
            mk_diff_row("kernel", "/vmlinuz", Ok("a1"), Ok("a2")),
            mk_diff_row("initrd", "/initrd.img", Ok("b1"), Ok("b2")),
            mk_diff_row("shim", "/EFI/BOOT/BOOTX64.EFI", Ok("c1"), Ok("c2")),
        ];
        let plan = plan_rotation(&diff);
        assert_eq!(plan.len(), 3);
        assert_eq!(plan[0].role, "kernel");
        assert_eq!(plan[1].role, "initrd");
        assert_eq!(plan[2].role, "shim");
    }

    fn mk_step(role: &'static str, esp_path: &'static str) -> RotationStep {
        RotationStep {
            role,
            esp_path,
            current_sha256: format!("{role}-cur"),
            fresh_sha256: format!("{role}-new"),
        }
    }

    #[test]
    fn rollback_plan_returns_empty_for_all_pending() {
        let progress = vec![
            StepProgress {
                step: mk_step("shim", "/EFI/BOOT/BOOTX64.EFI"),
                state: StepState::Pending,
            },
            StepProgress {
                step: mk_step("grub", "/EFI/BOOT/grubx64.efi"),
                state: StepState::Pending,
            },
        ];
        assert_eq!(rollback_plan(&progress), Vec::new());
    }

    #[test]
    fn rollback_plan_unwinds_in_reverse_order() {
        let progress = vec![
            StepProgress {
                step: mk_step("shim", "/EFI/BOOT/BOOTX64.EFI"),
                state: StepState::Rotated,
            },
            StepProgress {
                step: mk_step("grub", "/EFI/BOOT/grubx64.efi"),
                state: StepState::Rotated,
            },
            StepProgress {
                step: mk_step("kernel", "/vmlinuz"),
                state: StepState::Staged,
            },
            // Pending step — no rollback action.
            StepProgress {
                step: mk_step("initrd", "/initrd.img"),
                state: StepState::Pending,
            },
        ];
        let rb = rollback_plan(&progress);
        assert_eq!(
            rb,
            vec![
                // initrd pending → no action
                RollbackAction::DeleteStaged {
                    esp_path: "/vmlinuz",
                },
                RollbackAction::RestoreFromBak {
                    esp_path: "/EFI/BOOT/grubx64.efi",
                },
                RollbackAction::RestoreFromBak {
                    esp_path: "/EFI/BOOT/BOOTX64.EFI",
                },
            ]
        );
    }

    #[test]
    fn rollback_plan_mixed_rotated_and_staged() {
        let progress = vec![
            StepProgress {
                step: mk_step("shim", "/EFI/BOOT/BOOTX64.EFI"),
                state: StepState::Rotated,
            },
            StepProgress {
                step: mk_step("grub", "/EFI/BOOT/grubx64.efi"),
                state: StepState::Staged,
            },
        ];
        let rb = rollback_plan(&progress);
        // Reverse order: staged first, then rotated.
        assert_eq!(
            rb,
            vec![
                RollbackAction::DeleteStaged {
                    esp_path: "/EFI/BOOT/grubx64.efi",
                },
                RollbackAction::RestoreFromBak {
                    esp_path: "/EFI/BOOT/BOOTX64.EFI",
                },
            ]
        );
    }

    #[test]
    fn rollback_plan_single_staged() {
        let progress = vec![StepProgress {
            step: mk_step("initrd", "/initrd.img"),
            state: StepState::Staged,
        }];
        assert_eq!(
            rollback_plan(&progress),
            vec![RollbackAction::DeleteStaged {
                esp_path: "/initrd.img",
            }]
        );
    }

    #[test]
    fn rotation_sources_maps_canonical_roles_to_paths() {
        use std::path::Path;
        let shim = Path::new("/h/shim.efi");
        let grub = Path::new("/h/grubx64.efi");
        let grub_cfg = Path::new("/h/grub.cfg");
        let kernel = Path::new("/h/vmlinuz");
        let initrd = Path::new("/h/initrd.img");
        let sources = RotationSources {
            shim,
            grub,
            grub_cfg,
            kernel,
            combined_initrd: initrd,
        };

        assert_eq!(sources.source_for("shim"), Some(shim));
        assert_eq!(sources.source_for("grub"), Some(grub));
        assert_eq!(sources.source_for("kernel"), Some(kernel));
        assert_eq!(sources.source_for("initrd"), Some(initrd));
        // Two roles share the grub.cfg source — boot vs ubuntu paths
        // are both the same byte content on the stick.
        assert_eq!(sources.source_for("grub_cfg_boot"), Some(grub_cfg));
        assert_eq!(sources.source_for("grub_cfg_ubuntu"), Some(grub_cfg));
    }

    #[test]
    fn rotation_sources_returns_none_for_unknown_role() {
        use std::path::Path;
        let p = Path::new("/h/anything");
        let sources = RotationSources {
            shim: p,
            grub: p,
            grub_cfg: p,
            kernel: p,
            combined_initrd: p,
        };
        assert!(sources.source_for("").is_none());
        assert!(sources.source_for("bogus").is_none());
        // Case-sensitivity: roles are defined in the planner as
        // lowercase fixed strings — anything else is a planner/executor
        // drift bug that the executor turns into a hard error.
        assert!(sources.source_for("Shim").is_none());
        assert!(sources.source_for("KERNEL").is_none());
    }
}
