// SPDX-License-Identifier: MIT OR Apache-2.0

//! In-place signed-chain rotation planner (#181 Phase 2a).
//!
//! This module is the pure-fn planning layer for `aegis-boot update
//! --apply`. Given a Phase-1 ESP diff, it produces an ordered list
//! of rotation steps naming exactly what would be backed up, staged,
//! rotated, and verified on each of the 6 canonical ESP slots.
//!
//! **Phase 2a ships the planner + rollback analyzer + unit tests.**
//! No destructive code path is reachable in this PR — the CLI
//! surface (`--apply --experimental-apply`) dry-prints the plan
//! and returns without calling any mtools subprocess. Phase 2b
//! wires the executor (backup → stage → verify → rotate → verify
//! → leave .bak in place) with OVMF E2E validation.
//!
//! # Why split
//!
//! FAT32 has no journal. The "atomic" in `--atomic-replace` means
//! "bounded rollback + explicit verification," not "single-syscall
//! transaction." Shipping the planner first lets reviewers validate
//! the rotation shape (ordering, rollback semantics) without the
//! executor in scope. Phase 2b's review then focuses on one
//! question: "does the executor do what the planner said it would?"
//!
//! # What the planner produces
//!
//! One [`RotationStep`] per canonical ESP slot that [`would_change`]
//! (same predicate as Phase-1's `EspFileDiff::would_change`).
//! Unchanged slots are skipped entirely — the executor never
//! touches them. The plan also carries the expected pre- and
//! post-rotation sha256 per step, so the executor's post-rotate
//! verify has a concrete target rather than trusting the filesystem.
//!
//! # Rollback analyzer
//!
//! The executor may partially complete — say, files 1-3 rotated,
//! file 4 fails mid-copy. The rollback analyzer ([`rollback_plan`])
//! takes the set of *completed* rotations plus the set of *staged-
//! but-not-rotated* `.new` files and emits the unwind: restore
//! .bak on rotated files, delete .new on staged-but-not-rotated.
//!
//! # Out of scope for 2a
//!
//! - Subprocess execution (Phase 2b)
//! - CA signature verification on the staged bytes (Phase 3)
//! - TOCTOU + path-validation hardening (Phase 3)
//! - Attestation manifest `update_history` field (Phase 4)
//!
//! Tracking: epic [#181](https://github.com/williamzujkowski/aegis-boot/issues/181).

// Phase 2a ships `plan_rotation()` + `print_rotation_plan` as live
// code, but the executor-side types (`StepProgress`, `RollbackAction`,
// `rollback_plan`) have no consumer until Phase 2b wires the
// destructive executor. Keep them compiled + unit-tested now so the
// Phase 2b PR is "wire the planner's outputs into mtools calls",
// not "re-derive the rollback logic under review pressure."
#![allow(dead_code)]

use crate::update::EspFileDiff;

/// One ESP slot's worth of rotation work. Generated by
/// [`plan_rotation`] from a Phase-1 diff row.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct RotationStep {
    /// Role label — `shim`, `grub`, `grub_cfg_boot`,
    /// `grub_cfg_ubuntu`, `kernel`, `initrd`. Matches
    /// `EspFileDiff::role`.
    pub role: &'static str,
    /// Canonical ESP destination with leading `/`. Example:
    /// `/EFI/BOOT/BOOTX64.EFI`.
    pub esp_path: &'static str,
    /// Sha256 currently on the stick for this slot. The executor
    /// hashes the staged `.bak` copy and asserts this value matches
    /// — detects silent tampering between planner and executor runs.
    pub current_sha256: String,
    /// Sha256 the host-side source a fresh flash would install.
    /// The executor's post-rotate readback hashes the rotated
    /// destination and asserts this value matches.
    pub fresh_sha256: String,
}

/// Build the ordered rotation plan from a Phase-1 ESP diff.
///
/// Only slots where [`EspFileDiff::would_change`] is true produce
/// a step. Unchanged slots and UNKNOWN slots (either side's hash
/// couldn't be computed) are elided — the executor skips them
/// entirely. This matches the planner's contract: we only rotate
/// what we're confident differs, and the executor's job is to make
/// that change happen safely.
pub(crate) fn plan_rotation(diff: &[EspFileDiff]) -> Vec<RotationStep> {
    diff.iter()
        .filter(|row| row.would_change())
        .filter_map(|row| {
            // would_change() is only true when both sides are Ok(_);
            // the unwraps here are infallible under that invariant.
            // Defend with a match anyway so a future refactor of
            // would_change() can't silently produce a panicking
            // planner.
            let current = row.current.as_ref().ok()?.clone();
            let fresh = row.fresh.as_ref().ok()?.clone();
            Some(RotationStep {
                role: row.role,
                esp_path: row.esp_path,
                current_sha256: current,
                fresh_sha256: fresh,
            })
        })
        .collect()
}

/// Records the outcome of one rotation step's progress through the
/// executor. Used by [`rollback_plan`] to decide what to undo.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum StepState {
    /// Executor hasn't started this step yet.
    Pending,
    /// `.new` staged on the ESP, but the rename-over hasn't fired.
    /// Rollback: delete `.new`.
    Staged,
    /// Rename-over complete, file rotated in place; `.bak` exists.
    /// Rollback: delete rotated, rename `.bak` → original.
    Rotated,
}

/// Per-step progress tracking for the executor. One per
/// [`RotationStep`] in the same order as the plan.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) struct StepProgress {
    pub step: RotationStep,
    pub state: StepState,
}

/// One rollback action. The executor translates these into mtools
/// subprocess calls in Phase 2b; 2a just names them so the planner
/// logic is unit-testable without subprocess mocking.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum RollbackAction {
    /// `mdel ::/<esp_path>.new` — clean up a stage-only file.
    DeleteStaged { esp_path: &'static str },
    /// `mdel ::/<esp_path>` then `mren ::/<esp_path>.bak
    /// ::/<esp_path>` — restore the pre-rotation file from backup.
    RestoreFromBak { esp_path: &'static str },
}

/// Compute the rollback sequence for a partially-executed plan.
/// Walks the progress list in REVERSE order — the most-recent
/// rotation is undone first so any shared-parent-directory state
/// (if we ever grow that case) unwinds in last-in-first-out
/// order. Pending steps contribute no rollback actions.
///
/// Returns an empty Vec when no state-carrying step was reached
/// (all pending), which is the "nothing to undo" case the executor
/// hits when pre-flight validation fails before the first write.
pub(crate) fn rollback_plan(progress: &[StepProgress]) -> Vec<RollbackAction> {
    progress
        .iter()
        .rev()
        .filter_map(|p| match p.state {
            StepState::Pending => None,
            StepState::Staged => Some(RollbackAction::DeleteStaged {
                esp_path: p.step.esp_path,
            }),
            StepState::Rotated => Some(RollbackAction::RestoreFromBak {
                esp_path: p.step.esp_path,
            }),
        })
        .collect()
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::missing_panics_doc
)]
mod tests {
    use super::*;

    fn mk_diff_row(
        role: &'static str,
        esp_path: &'static str,
        current: Result<&str, &str>,
        fresh: Result<&str, &str>,
    ) -> EspFileDiff {
        EspFileDiff {
            role,
            esp_path,
            current: current.map(str::to_string).map_err(str::to_string),
            fresh: fresh.map(str::to_string).map_err(str::to_string),
        }
    }

    #[test]
    fn plan_rotation_skips_unchanged_and_unknown_rows() {
        let diff = vec![
            // Unchanged — same hash both sides → skip.
            mk_diff_row("shim", "/EFI/BOOT/BOOTX64.EFI", Ok("a"), Ok("a")),
            // Changed — would rotate.
            mk_diff_row("grub", "/EFI/BOOT/grubx64.efi", Ok("b"), Ok("c")),
            // UNKNOWN (current side errored) — skip.
            mk_diff_row("kernel", "/vmlinuz", Err("no mtype"), Ok("d")),
            // UNKNOWN (fresh side errored) — skip.
            mk_diff_row("initrd", "/initrd.img", Ok("e"), Err("missing src")),
            // Another changed one.
            mk_diff_row("grub_cfg_boot", "/EFI/BOOT/grub.cfg", Ok("f"), Ok("g")),
        ];
        let plan = plan_rotation(&diff);
        assert_eq!(plan.len(), 2, "only CHANGED rows should produce a step");
        assert_eq!(plan[0].role, "grub");
        assert_eq!(plan[0].current_sha256, "b");
        assert_eq!(plan[0].fresh_sha256, "c");
        assert_eq!(plan[1].role, "grub_cfg_boot");
    }

    #[test]
    fn plan_rotation_preserves_diff_order() {
        // Ensure the planner doesn't reshuffle — order matters for
        // the executor's pre-verify chain (each step depends on
        // the prior one having committed).
        let diff = vec![
            mk_diff_row("kernel", "/vmlinuz", Ok("a1"), Ok("a2")),
            mk_diff_row("initrd", "/initrd.img", Ok("b1"), Ok("b2")),
            mk_diff_row("shim", "/EFI/BOOT/BOOTX64.EFI", Ok("c1"), Ok("c2")),
        ];
        let plan = plan_rotation(&diff);
        assert_eq!(plan.len(), 3);
        assert_eq!(plan[0].role, "kernel");
        assert_eq!(plan[1].role, "initrd");
        assert_eq!(plan[2].role, "shim");
    }

    fn mk_step(role: &'static str, esp_path: &'static str) -> RotationStep {
        RotationStep {
            role,
            esp_path,
            current_sha256: format!("{role}-cur"),
            fresh_sha256: format!("{role}-new"),
        }
    }

    #[test]
    fn rollback_plan_returns_empty_for_all_pending() {
        let progress = vec![
            StepProgress {
                step: mk_step("shim", "/EFI/BOOT/BOOTX64.EFI"),
                state: StepState::Pending,
            },
            StepProgress {
                step: mk_step("grub", "/EFI/BOOT/grubx64.efi"),
                state: StepState::Pending,
            },
        ];
        assert_eq!(rollback_plan(&progress), Vec::new());
    }

    #[test]
    fn rollback_plan_unwinds_in_reverse_order() {
        let progress = vec![
            StepProgress {
                step: mk_step("shim", "/EFI/BOOT/BOOTX64.EFI"),
                state: StepState::Rotated,
            },
            StepProgress {
                step: mk_step("grub", "/EFI/BOOT/grubx64.efi"),
                state: StepState::Rotated,
            },
            StepProgress {
                step: mk_step("kernel", "/vmlinuz"),
                state: StepState::Staged,
            },
            // Pending step — no rollback action.
            StepProgress {
                step: mk_step("initrd", "/initrd.img"),
                state: StepState::Pending,
            },
        ];
        let rb = rollback_plan(&progress);
        assert_eq!(
            rb,
            vec![
                // initrd pending → no action
                RollbackAction::DeleteStaged {
                    esp_path: "/vmlinuz",
                },
                RollbackAction::RestoreFromBak {
                    esp_path: "/EFI/BOOT/grubx64.efi",
                },
                RollbackAction::RestoreFromBak {
                    esp_path: "/EFI/BOOT/BOOTX64.EFI",
                },
            ]
        );
    }

    #[test]
    fn rollback_plan_mixed_rotated_and_staged() {
        let progress = vec![
            StepProgress {
                step: mk_step("shim", "/EFI/BOOT/BOOTX64.EFI"),
                state: StepState::Rotated,
            },
            StepProgress {
                step: mk_step("grub", "/EFI/BOOT/grubx64.efi"),
                state: StepState::Staged,
            },
        ];
        let rb = rollback_plan(&progress);
        // Reverse order: staged first, then rotated.
        assert_eq!(
            rb,
            vec![
                RollbackAction::DeleteStaged {
                    esp_path: "/EFI/BOOT/grubx64.efi",
                },
                RollbackAction::RestoreFromBak {
                    esp_path: "/EFI/BOOT/BOOTX64.EFI",
                },
            ]
        );
    }

    #[test]
    fn rollback_plan_single_staged() {
        let progress = vec![StepProgress {
            step: mk_step("initrd", "/initrd.img"),
            state: StepState::Staged,
        }];
        assert_eq!(
            rollback_plan(&progress),
            vec![RollbackAction::DeleteStaged {
                esp_path: "/initrd.img",
            }]
        );
    }
}
